server:
  ###服务端口号
  port: 80
spring: 
  application: 
  ###服务别名--服务注册到注册中心名称
    name: its-spb-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        ###自定义服务路由名称(名称自定义)
      - id: its-spb-base-servers
        ###lb代表从注册中心获取服务 整合ribbon 自动实现负载均衡
        uri: lb://its-spb-base-servers
        predicates:
            ###当客户端请求http://127.0.0.1:80/api-base开头的都会转发到Base服务
          - Path=/api-base/**
        filters:
            ###设置StripPrefix=1,去掉前缀,否则访问服务时会带上/api-base
          - StripPrefix=1
          ###设置PrefixPath=/mypath,添加前缀,访问服务时会带上/mypath
          ###- PrefixPath=/mypath
          - RequestTime=true
        ###自定义服务路由名称(名称自定义)
      - id: its-spb-order-servers
        ###lb代表从注册中心获取服务 整合ribbon 自动实现负载均衡
        uri: lb://its-spb-order-servers
        predicates:
            ###当客户端请求http://127.0.0.1:80/api-order开头的都会转发到Order服务
          - Path=/api-order/**
        filters:
          - StripPrefix=1
          - RequestTime=true
          
          
#  cloud:
#    gateway:
#      filter:
#        remove-non-proxy-headers:
#          headers:
#          - dummy
#      routes:
#        - id:  apiuser
#        # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
#          uri: lb://user-service
#          predicates:
#          # 重点！转发该路径！,/userapi/**,
#          - Path=/its-base/**
#          # http://localhost:6601/userapi/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上userapi
#          #而不是我们期望的去掉userapi，只保留**部分
#          filters:
#          - StripPrefix=1
#        - id:  api2user
#          uri: lb://user-service
#          predicates:
#          - Path=/userapi2/**
#          filters:
#          - StripPrefix=1
          
          
#Eureka注册中心配置
eureka:
  client:
    serviceUrl:
    ###注册地址
      defaultZone: http://127.0.0.1:8101/eureka/    
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000