#开发环境配置文件
server:
   #配置server端口
   port: 8080
   #配置上下文
   #servlet:
   #   context-path: /its
  #session过期时间
   servlet:
     session:
       timeout: 1800s
spring:
  profiles:
    ###引用其他的yml文件
    include: mybatis,redis

#指定日志配置
logging:
  config: classpath:log4j2.yml
