#Springboot2.X版本配置Redis
spring:
   redis:
      #单节点
      host: 10.202.107.207
      port: 6379
      #哨兵模式
      #sentinel:
      #   master: its_sentinel
      #   nodes: 
      #      - vm-01-ip:26379
      #      - vm-02-ip:26379
      #      - vm-03-ip:26379
      #密码
      password: 123456
      lettuce:
         pool:
           ### 连接池最大连接数（使用负值表示没有限制） 
           max-active: 9
           ### 连接池最大阻塞等待时间（使用负值表示没有限制）
           max-wait: -1
           ### 连接池中的最大空闲连接 
           max-idle: 9
           ### 连接池中的最小空闲连接 
           min-idle: 0
   ### Redis数据库索引(默认为0) 
   database: 0
   ### 连接超时时间（毫秒） 
   timeout: 60000